# Shell variables
# Generated by 'wal'
wallpaper='/home/ajinis/Pictures/wallpaper/735756.png'

# Special
background='#291318'
foreground='#f2e6e3'
cursor='#f2e6e3'

# Colors
color0='#291318'
color1='#C7A29A'
color2='#C9AEAE'
color3='#FEBAB5'
color4='#F6C7B4'
color5='#D8BBC2'
color6='#F8D1D0'
color7='#f2e6e3'
color8='#a9a19e'
color9='#C7A29A'
color10='#C9AEAE'
color11='#FEBAB5'
color12='#F6C7B4'
color13='#D8BBC2'
color14='#F8D1D0'
color15='#f2e6e3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
