--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ajinis/Pictures/wallpaper/735756.png"

-- Special
background="#291318"
foreground="#f2e6e3"
cursor="#f2e6e3"

-- Colors
color0="#291318"
color1="#C7A29A"
color2="#C9AEAE"
color3="#FEBAB5"
color4="#F6C7B4"
color5="#D8BBC2"
color6="#F8D1D0"
color7="#f2e6e3"
color8="#a9a19e"
color9="#C7A29A"
color10="#C9AEAE"
color11="#FEBAB5"
color12="#F6C7B4"
color13="#D8BBC2"
color14="#F8D1D0"
color15="#f2e6e3"
