--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ajinis/Pictures/wallpaper/eva.png"

-- Special
background="#0B0D0A"
foreground="#f0f2df"
cursor="#f0f2df"

-- Colors
color0="#0B0D0A"
color1="#DB512E"
color2="#708E62"
color3="#A29360"
color4="#D8A55C"
color5="#77A786"
color6="#C0CAA2"
color7="#f0f2df"
color8="#a8a99c"
color9="#DB512E"
color10="#708E62"
color11="#A29360"
color12="#D8A55C"
color13="#77A786"
color14="#C0CAA2"
color15="#f0f2df"
