# Shell variables
# Generated by 'wal'
wallpaper='/home/ajinis/Pictures/wallpaper/eva.png'

# Special
background='#0B0D0A'
foreground='#f0f2df'
cursor='#f0f2df'

# Colors
color0='#0B0D0A'
color1='#DB512E'
color2='#708E62'
color3='#A29360'
color4='#D8A55C'
color5='#77A786'
color6='#C0CAA2'
color7='#f0f2df'
color8='#a8a99c'
color9='#DB512E'
color10='#708E62'
color11='#A29360'
color12='#D8A55C'
color13='#77A786'
color14='#C0CAA2'
color15='#f0f2df'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
